package com.fis.springjpa.employee;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/employee") // This means URL's start with /demo (after Application path)
public class EmployeeMainController {
  @Autowired // This means to get the bean called employeeRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private EmployeeRepository employeeRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewEmployee (@RequestParam int id
      , @RequestParam String name) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Employee n = new Employee();
    n.setId(id);
    n.setName(name);
   
    employeeRepository.save(n);
    return "Saved employee details";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Employee> getAllUsers() {
    // This returns a JSON or XML with the users
    return employeeRepository.findAll();
  }

}